Home Task - Building Blocks of OOP, Part 2
jafrias2159/software-designs-and-algorithms pull request #2
Opened 2022-07-12 15:00 UTC by jafrias2159

Classes & interfaces for the home task, part 2:
Bow
Comparabale,
Consumable,
Item,
Sword,
etc...

2022-07-12 19:59 UTC, vsuazerEPAM requested changes

2022-07-12 19:59 UTC, vsuazerEPAM commented on docs/3-building-blocks-of-oop-part-2/hometask/src/Inventory.ts
> +      // Sort by any characteritcs in array
In this part, isn’t supposed to do what the comment says?

2022-07-13 14:44 UTC, jafrias2159 commented on docs/3-building-blocks-of-oop-part-2/hometask/src/Inventory.ts
> +      // Sort by any characteritcs in array
Good catch, I added the missing logic to sort the inventory items.

2022-07-14 02:58 UTC, vsuazerEPAM approved these changes

2022-07-18 19:19 UTC, merged